### PR TITLE
Using MessagePackage as argument of a Receiver method

### PR DESCRIPTION
**Pull request by giolaq**
Missing ForceMessageEvent, everything is ok using MessagePackage in Receiver.

### CODE REVIEW

**Comment by jorishermans** [comment]
Thanks! Indeed based upon an older version, going to work on this example to finish his functionality ;)

**Comment by giolaq** [comment]
I'm studying the examples, maybe I can help. At the end of March I want to do a talk about Dart and some cool packages, I chose StageXL, Polymer and Dart Force :)

**Comment by jorishermans** [comment]
It would be great if you could help me, every suggestion on new features, documentation improvements are welcome ;-) or even help on existing examples!

Also if you like to contribute on the framework it self ;-)

These are my plans next to revamp this example:
An example with polymer (todo alike) and another example together with shelf.
If you could assist in any of these ... or just make this example better ...

**Comment by jorishermans** [comment]
I am thinking of creating poly force, a combination package of force and polymer with custom force polymer elements in ... is that something usefull?

**Comment by giolaq** [comment]
I think this could be very usefull

**Pull request merged**
